/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.intersys.iamas.sistema;

import javax.swing.JDialog;

/**
 *
 * @author PROGRAMADOR-02
 */
public class GrupoView extends JDialog {

	private static GrupoView instncia;

	public static synchronized GrupoView getInstancia() {
		if (instncia == null) {
			instncia = new GrupoView();
		}
		return instncia;
	}

	/**
	 * Creates new form GrupoView
	 */
	public GrupoView() {
		initComponents();
		this.inicializar();
		this.setModal(rootPaneCheckingEnabled);
	}

	private void inicializar() {
		GrupoViewCtrl grupoViewCtrl = GrupoViewCtrl.getInstancia();
		grupoViewCtrl.setGrupoView(this);
		grupoViewCtrl.inicialiazar();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnPrevius = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        tfPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jComboBoxPesquisa = new javax.swing.JComboBox<>();
        btnSair = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        lebalCodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNomeDoGrupo = new javax.swing.JTextField();
        lbCodigoDoGrupo = new javax.swing.JLabel();
        jPanelLista = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaGrupo = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");

        btnAlterar.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/edit.png"))); // NOI18N
        btnAlterar.setText("Alterar");

        btnPrevius.setBackground(new java.awt.Color(255, 255, 255));
        btnPrevius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/previous.png"))); // NOI18N

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/skip.png"))); // NOI18N

        btnNovo.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/plus.png"))); // NOI18N
        btnNovo.setText("Novo");

        btnPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisa.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/looking.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");

        jComboBoxPesquisa.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jComboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Grupo" }));

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/logout.png"))); // NOI18N
        btnSair.setText("Sair");

        btnLast.setBackground(new java.awt.Color(255, 255, 255));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/last.png"))); // NOI18N

        lebalCodigo.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lebalCodigo.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel2.setText("Nome do Grupo:");

        tfNomeDoGrupo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lbCodigoDoGrupo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lebalCodigo))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(lbCodigoDoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfNomeDoGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lebalCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCodigoDoGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNomeDoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanelCadastro);

        TabelaGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Do Grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelaGrupo);
        if (TabelaGrupo.getColumnModel().getColumnCount() > 0) {
            TabelaGrupo.getColumnModel().getColumn(0).setMinWidth(100);
            TabelaGrupo.getColumnModel().getColumn(0).setPreferredWidth(80);
            TabelaGrupo.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        javax.swing.GroupLayout jPanelListaLayout = new javax.swing.GroupLayout(jPanelLista);
        jPanelLista.setLayout(jPanelListaLayout);
        jPanelListaLayout.setHorizontalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        jPanelListaLayout.setVerticalGroup(
            jPanelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista", jPanelLista);

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        btnFast.setBackground(new java.awt.Color(255, 255, 255));
        btnFast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/fast.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxPesquisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPrevius, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFast, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addComponent(jTabbedPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrevius, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLast)
                            .addComponent(btnFast))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GrupoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GrupoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GrupoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GrupoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GrupoView().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaGrupo;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFast;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPrevius;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> jComboBoxPesquisa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelLista;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCodigoDoGrupo;
    private javax.swing.JLabel lebalCodigo;
    private javax.swing.JTextField tfNomeDoGrupo;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables

	public javax.swing.JButton getBtnAlterar() {
		return btnAlterar;
	}

	public void setBtnAlterar(javax.swing.JButton btnAlterar) {
		this.btnAlterar = btnAlterar;
	}

	public javax.swing.JButton getBtnExcluir() {
		return btnExcluir;
	}

	public void setBtnExcluir(javax.swing.JButton btnExcluir) {
		this.btnExcluir = btnExcluir;
	}

	public javax.swing.JButton getBtnNext() {
		return btnNext;
	}

	public void setBtnNext(javax.swing.JButton btnNext) {
		this.btnNext = btnNext;
	}

	public javax.swing.JButton getBtnPrevius() {
		return btnPrevius;
	}

	public void setBtnPrevius(javax.swing.JButton btnPrevius) {
		this.btnPrevius = btnPrevius;
	}

	public javax.swing.JButton getBtnNovo() {
		return btnNovo;
	}

	public void setBtnNovo(javax.swing.JButton btnNovo) {
		this.btnNovo = btnNovo;
	}

	public javax.swing.JButton getBtnPesquisa() {
		return btnPesquisa;
	}

	public void setBtnPesquisa(javax.swing.JButton btnPesquisa) {
		this.btnPesquisa = btnPesquisa;
	}

	public javax.swing.JComboBox<String> getjComboBoxPesquisa() {
		return jComboBoxPesquisa;
	}

	public void setjComboBoxPesquisa(javax.swing.JComboBox<String> jComboBoxPesquisa) {
		this.jComboBoxPesquisa = jComboBoxPesquisa;
	}

	public javax.swing.JTextField getTfPesquisa() {
		return tfPesquisa;
	}

	public void setTfPesquisa(javax.swing.JTextField tfPesquisa) {
		this.tfPesquisa = tfPesquisa;
	}

	public javax.swing.JButton getBtnSair() {
		return btnSair;
	}

	public javax.swing.JButton getBtnFast() {
		return btnFast;
	}

	public void setBtnFast(javax.swing.JButton btnFast) {
		this.btnFast = btnFast;
	}

	public javax.swing.JButton getBtnLast() {
		return btnLast;
	}

	public void setBtnLast(javax.swing.JButton btnLast) {
		this.btnLast = btnLast;
	}

	public void setBtnSair(javax.swing.JButton btnSair) {
		this.btnSair = btnSair;
	}

	public javax.swing.JTable getTabelaGrupo() {
		return TabelaGrupo;
	}

	public void setTabelaGrupo(javax.swing.JTable tabelaGrupo) {
		TabelaGrupo = tabelaGrupo;
	}

	public javax.swing.JButton getBtnCancelar() {
		return btnCancelar;
	}

	public void setBtnCancelar(javax.swing.JButton btnCancelar) {
		this.btnCancelar = btnCancelar;
	}

	public javax.swing.JButton getBtnSalvar() {
		return btnSalvar;
	}

	public void setBtnSalvar(javax.swing.JButton btnSalvar) {
		this.btnSalvar = btnSalvar;
	}

	public javax.swing.JLabel getLbCodigoDoGrupo() {
		return lbCodigoDoGrupo;
	}

	public void setLbCodigoDoGrupo(javax.swing.JLabel lbCodigoDoGrupo) {
		this.lbCodigoDoGrupo = lbCodigoDoGrupo;
	}

	public javax.swing.JLabel getLebalCodigo() {
		return lebalCodigo;
	}

	public void setLebalCodigo(javax.swing.JLabel lebalCodigo) {
		this.lebalCodigo = lebalCodigo;
	}

	public javax.swing.JTextField getTfNomeDoGrupo() {
		return tfNomeDoGrupo;
	}

	public void setTfNomeDoGrupo(javax.swing.JTextField tfNomeDoGrupo) {
		this.tfNomeDoGrupo = tfNomeDoGrupo;
	}

	public javax.swing.JPanel getjPanelCadastro() {
		return jPanelCadastro;
	}

	public void setjPanelCadastro(javax.swing.JPanel jPanelCadastro) {
		this.jPanelCadastro = jPanelCadastro;
	}

	public javax.swing.JPanel getjPanelLista() {
		return jPanelLista;
	}

	public void setjPanelLista(javax.swing.JPanel jPanelLista) {
		this.jPanelLista = jPanelLista;
	}

	public javax.swing.JTabbedPane getjTabbedPane1() {
		return jTabbedPane1;
	}

	public void setjTabbedPane1(javax.swing.JTabbedPane jTabbedPane1) {
		this.jTabbedPane1 = jTabbedPane1;
	}
	
	

}
