package com.intersys.iamas.sistema;

/**
 *
 * @author PROGRAMADOR-02
 */
public final class ProdutoView extends javax.swing.JFrame {

	/**
	 * Creates new form ProdutoView
	 */
	public ProdutoView() {
		this.initComponents();
		this.inicializar();
	}

	private void inicializar() {
		ProdutoViewCtrl produtoViewCtrl = ProdutoViewCtrl.getInstancia();
		produtoViewCtrl.setProdutoView(this);
		produtoViewCtrl.inicializar();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelCombobox = new javax.swing.JPanel();
        jComboBoxLista = new javax.swing.JComboBox<>();
        tfCombobox = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jtPainelComGuias = new javax.swing.JTabbedPane();
        jPainelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfCodProduto = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        tfCodGrupo = new javax.swing.JTextField();
        tfGrupo = new javax.swing.JTextField();
        tfCodSubGrupo = new javax.swing.JTextField();
        tfSubGrupo = new javax.swing.JTextField();
        tfEspecie = new javax.swing.JTextField();
        tfEstoque = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        jPainelLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabeleLista = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnMenor = new javax.swing.JButton();
        btnMaior = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnFast = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jPanelCombobox.setBackground(java.awt.SystemColor.controlHighlight);

        jComboBoxLista.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jComboBoxLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Descrição" }));

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/looking.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout jPanelComboboxLayout = new javax.swing.GroupLayout(jPanelCombobox);
        jPanelCombobox.setLayout(jPanelComboboxLayout);
        jPanelComboboxLayout.setHorizontalGroup(
            jPanelComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComboboxLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jComboBoxLista, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCombobox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        jPanelComboboxLayout.setVerticalGroup(
            jPanelComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComboboxLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelComboboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxLista)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCombobox))
                .addGap(5, 5, 5))
        );

        jtPainelComGuias.setBackground(new java.awt.Color(81, 124, 154));
        jtPainelComGuias.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N

        jPainelCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("CodProduto");

        jLabel2.setText("Descrição");

        jLabel3.setText("Grupo");

        jLabel4.setText("SubGrupo");

        jLabel5.setText("Espécie");

        jLabel6.setText("Estoque");

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/eraser.png"))); // NOI18N
        btnLimpar.setText("Limpar");

        javax.swing.GroupLayout jPainelCadastroLayout = new javax.swing.GroupLayout(jPainelCadastro);
        jPainelCadastro.setLayout(jPainelCadastroLayout);
        jPainelCadastroLayout.setHorizontalGroup(
            jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfEspecie, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPainelCadastroLayout.createSequentialGroup()
                            .addComponent(tfCodSubGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfSubGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                        .addGroup(jPainelCadastroLayout.createSequentialGroup()
                            .addComponent(tfCodGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfGrupo))
                        .addComponent(tfDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPainelCadastroLayout.createSequentialGroup()
                            .addComponent(tfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPainelCadastroLayout.setVerticalGroup(
            jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodSubGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSubGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jtPainelComGuias.addTab("Cadastro", jPainelCadastro);

        jPainelLista.setBackground(new java.awt.Color(255, 255, 255));

        jTabeleLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Grupo", "SubGrupo", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabeleLista.setGridColor(new java.awt.Color(255, 255, 255));
        jTabeleLista.setSelectionBackground(new java.awt.Color(248, 248, 14));
        jScrollPane1.setViewportView(jTabeleLista);

        javax.swing.GroupLayout jPainelListaLayout = new javax.swing.GroupLayout(jPainelLista);
        jPainelLista.setLayout(jPainelListaLayout);
        jPainelListaLayout.setHorizontalGroup(
            jPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );
        jPainelListaLayout.setVerticalGroup(
            jPainelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );

        jtPainelComGuias.addTab("Lista", jPainelLista);

        btnNovo.setBackground(new java.awt.Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/plus.png"))); // NOI18N
        btnNovo.setText("Novo");

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        btnAlterar.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/edit.png"))); // NOI18N
        btnAlterar.setText("Alterar");

        btnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");

        btnMenor.setBackground(new java.awt.Color(255, 255, 255));
        btnMenor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/previous.png"))); // NOI18N

        btnMaior.setBackground(new java.awt.Color(255, 255, 255));
        btnMaior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/skip.png"))); // NOI18N

        btnLast.setBackground(new java.awt.Color(255, 255, 255));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/last.png"))); // NOI18N

        btnFast.setBackground(new java.awt.Color(255, 255, 255));
        btnFast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/intersys/iamas/sistema/imagens/fast.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLast, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(btnMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMaior, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(btnFast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanelCombobox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPainelComGuias)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanelCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPainelComGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMaior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ProdutoView().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFast;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMaior;
    private javax.swing.JButton btnMenor;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> jComboBoxLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPainelCadastro;
    private javax.swing.JPanel jPainelLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCombobox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabeleLista;
    private javax.swing.JTabbedPane jtPainelComGuias;
    private javax.swing.JTextField tfCodGrupo;
    private javax.swing.JTextField tfCodProduto;
    private javax.swing.JTextField tfCodSubGrupo;
    private javax.swing.JTextField tfCombobox;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfEspecie;
    private javax.swing.JTextField tfEstoque;
    private javax.swing.JTextField tfGrupo;
    private javax.swing.JTextField tfSubGrupo;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JButton getBtnAlterar() {
		return btnAlterar;
	}

	public void setBtnAlterar(javax.swing.JButton btnAlterar) {
		this.btnAlterar = btnAlterar;
	}

	public javax.swing.JButton getBtnCancelar() {
		return btnCancelar;
	}

	public void setBtnCancelar(javax.swing.JButton btnCancelar) {
		this.btnCancelar = btnCancelar;
	}

	public javax.swing.JButton getBtnExcluir() {
		return btnExcluir;
	}

	public void setBtnExcluir(javax.swing.JButton btnExcluir) {
		this.btnExcluir = btnExcluir;
	}

	public javax.swing.JButton getBtnNovo() {
		return btnNovo;
	}

	public void setBtnNovo(javax.swing.JButton btnNovo) {
		this.btnNovo = btnNovo;
	}

	public javax.swing.JButton getBtnPesquisar() {
		return btnPesquisar;
	}

	public void setBtnPesquisar(javax.swing.JButton btnPesquisar) {
		this.btnPesquisar = btnPesquisar;
	}

	public javax.swing.JButton getBtnSalvar() {
		return btnSalvar;
	}

	public void setBtnSalvar(javax.swing.JButton btnSalvar) {
		this.btnSalvar = btnSalvar;
	}

	public javax.swing.JComboBox<String> getjComboBox() {
		return jComboBoxLista;
	}

	public void setjComboBox(javax.swing.JComboBox<String> jComboBox) {
		this.jComboBoxLista = jComboBox;
	}

	public javax.swing.JPanel getjPainelCadastro() {
		return jPainelCadastro;
	}

	public void setjPainelCadastro(javax.swing.JPanel jPainelCadastro) {
		this.jPainelCadastro = jPainelCadastro;
	}

	public javax.swing.JPanel getjPainelLista() {
		return jPainelLista;
	}

	public void setjPainelLista(javax.swing.JPanel jPainelLista) {
		this.jPainelLista = jPainelLista;
	}

	public javax.swing.JTable getjTabeleLista() {
		return jTabeleLista;
	}

	public void setjTabeleLista(javax.swing.JTable jTabeleLista) {
		this.jTabeleLista = jTabeleLista;
	}

	public javax.swing.JTextField getTfCodGrupo() {
		return tfCodGrupo;
	}

	public void setTfCodGrupo(javax.swing.JTextField tfCodGrupo) {
		this.tfCodGrupo = tfCodGrupo;
	}

	public javax.swing.JTextField getTfCodProduto() {
		return tfCodProduto;
	}

	public void setTfCodProduto(javax.swing.JTextField tfCodProduto) {
		this.tfCodProduto = tfCodProduto;
	}

	public javax.swing.JTextField getTfCodSubGrupo() {
		return tfCodSubGrupo;
	}

	public void setTfCodSubGrupo(javax.swing.JTextField tfCodSubGrupo) {
		this.tfCodSubGrupo = tfCodSubGrupo;
	}

	public javax.swing.JTextField getTfCombobox() {
		return tfCombobox;
	}

	public void setTfCombobox(javax.swing.JTextField tfCombobox) {
		this.tfCombobox = tfCombobox;
	}

	public javax.swing.JTextField getTfDescricao() {
		return tfDescricao;
	}

	public void setTfDescricao(javax.swing.JTextField tfDescricao) {
		this.tfDescricao = tfDescricao;
	}

	public javax.swing.JTextField getTfEspecie() {
		return tfEspecie;
	}

	public void setTfEspecie(javax.swing.JTextField tfEspecie) {
		this.tfEspecie = tfEspecie;
	}

	public javax.swing.JTextField getTfEstoque() {
		return tfEstoque;
	}

	public void setTfEstoque(javax.swing.JTextField tfEstoque) {
		this.tfEstoque = tfEstoque;
	}

	public javax.swing.JTextField getTfGrupo() {
		return tfGrupo;
	}

	public void setTfGrupo(javax.swing.JTextField tfGrupo) {
		this.tfGrupo = tfGrupo;
	}

	public javax.swing.JTextField getTfSubGrupo() {
		return tfSubGrupo;
	}

	public void setTfSubGrupo(javax.swing.JTextField tfSubGrupo) {
		this.tfSubGrupo = tfSubGrupo;
	}

	public javax.swing.JTabbedPane getJtPainelComGuias() {
		return jtPainelComGuias;
	}

	public void setJtPainelComGuias(javax.swing.JTabbedPane jtPainelComGuias) {
		this.jtPainelComGuias = jtPainelComGuias;
	}

	public javax.swing.JButton getBtnLimpar() {
		return btnLimpar;
	}

	public void setBtnLimpar(javax.swing.JButton btnLimpar) {
		this.btnLimpar = btnLimpar;
	}

	public javax.swing.JButton getBtnMaior() {
		return btnMaior;
	}

	public void setBtnMaior(javax.swing.JButton btnMaior) {
		this.btnMaior = btnMaior;
	}

	public javax.swing.JButton getBtnMenor() {
		return btnMenor;
	}

	public void setBtnMenor(javax.swing.JButton btnMenor) {
		this.btnMenor = btnMenor;
	}

	public javax.swing.JComboBox<String> getjComboBoxLista() {
		return jComboBoxLista;
	}

	public void setjComboBoxLista(javax.swing.JComboBox<String> jComboBoxLista) {
		this.jComboBoxLista = jComboBoxLista;
	}

	public javax.swing.JPanel getjPanelCombobox() {
		return jPanelCombobox;
	}

	public void setjPanelCombobox(javax.swing.JPanel jPanelCombobox) {
		this.jPanelCombobox = jPanelCombobox;
	}

	public javax.swing.JButton getBtnFast() {
		return btnFast;
	}

	public void setBtnFast(javax.swing.JButton btnFast) {
		this.btnFast = btnFast;
	}

	public javax.swing.JButton getBtnLast() {
		return btnLast;
	}

	public void setBtnLast(javax.swing.JButton btnLast) {
		this.btnLast = btnLast;
	}
	
	

}
